services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: backend
    volumes:
      - ..:/app
    working_dir: /build
    env_file:
      - ../.env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    command: ["/build/balloon-shop"]
    ports:
      - "8080:8080"

  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - ../.env
    volumes:
      - balloon_shop_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 30s
      retries: 5
      start_period: 1m
      timeout: 10s
    ports:
      - "5433:5432"

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:nightly
    env_file:
      - ../.env
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  balloon_shop_db_data:
  rabbitmq_data: