name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Go Tests and Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into the server and deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_SERVER_IP }} << 'EOF'
            cd /home/balloon-shop
            git fetch origin
            git checkout master
            git reset --hard origin/master
          
            cd deploy
            sudo docker-compose down
            chmod +x ./db-healthcheck.sh
            sudo docker-compose up -d --build
            echo "Docker Compose deployment completed."
          
            # Wait for DB to be ready
            echo "Waiting for Postgres to be ready..."
            until sudo docker exec db pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
              echo "Postgres is unavailable - sleeping"
              sleep 2
            done
            echo "Postgres is ready!"
          
            # Run DB migrations
            echo "Running database migrations..."
            if ! sudo docker exec -t backend sh -c 'migrate -path ./infrastructure/db/migrations -database "$DATABASE_URL" up'; then
              echo "ERROR: Database migrations failed. Aborting deployment."
              exit 1
            fi
          
            # Fill slugs
            echo "Filling slugs..."
            sudo docker exec -t backend sh -c 'cd /build && ./fill_slugs'
          
            # Generate sitemap
            echo "Generating sitemap..."
            sudo docker exec -t backend sh -c 'cd /build && ./generate_sitemap'
          EOF
